<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>75. Credit Transfer - Failed - Invalid Mandatory Field Fee Amount</name>
   <tag></tag>
   <elementGuidId>c922651d-97f6-4618-9d76-cea613257797</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;creditTransferRequest\&quot;: {\n        \&quot;transactionId\&quot;: \&quot;${transactionId}\&quot;,\n        \&quot;institutionBic\&quot;: \&quot;${institutionBic}\&quot;,\n        \&quot;channelType\&quot;: \&quot;${channelType}\&quot;,\n        \&quot;branchCode\&quot;: \&quot;${branchCode}\&quot;,\n        \&quot;branchInput\&quot;: \&quot;${branchInput}\&quot;,\n        \&quot;branchFee\&quot;: \&quot;${branchFee}\&quot;,\n        \&quot;debitedAccountName\&quot;: \&quot;${debitedAccountName}\&quot;,\n        \&quot;debitedAccountNumber\&quot;: \&quot;${debitedAccountNumber}\&quot;,\n        \&quot;debitedAccountType\&quot;: \&quot;${debitedAccountType}\&quot;,\n        \&quot;debitedCityCode\&quot;: \&quot;${debitedCityCode}\&quot;,\n        \&quot;debitedId\&quot;: \&quot;${debitedId}\&quot;,\n        \&quot;debitedResidentStatus\&quot;: \&quot;${debitedResidentStatus}\&quot;,\n        \&quot;debitedType\&quot;: \&quot;${debitedType}\&quot;,\n        \&quot;creditedAccountName\&quot;: \&quot;${creditedAccountName}\&quot;,\n        \&quot;creditedAccountNumber\&quot;: \&quot;${creditedAccountNumber}\&quot;,\n        \&quot;creditedAccountType\&quot;: \&quot;${creditedAccountType}\&quot;,\n        \&quot;creditedBic\&quot;: \&quot;${creditedBic}\&quot;,\n        \&quot;creditedCityCode\&quot;: \&quot;${creditedCityCode}\&quot;,\n        \&quot;creditedId\&quot;: \&quot;${creditedId}\&quot;,\n        \&quot;creditedProxyAlias\&quot;: \&quot;${creditedProxyAlias}\&quot;,\n        \&quot;creditedProxyType\&quot;: \&quot;${creditedProxyType}\&quot;,\n        \&quot;creditedResidentStatus\&quot;: \&quot;${creditedResidentStatus}\&quot;,\n        \&quot;creditedType\&quot;: \&quot;${creditedType}\&quot;,\n        \&quot;categoryPurpose\&quot;: \&quot;${categoryPurpose}\&quot;,\n        \&quot;chargeType\&quot;: \&quot;${chargeType}\&quot;,\n        \&quot;trxAmount\&quot;: \&quot;${trxAmount}\&quot;,\n        \&quot;feeAmount1\&quot;: \&quot;${feeAmount}\&quot;,\n        \&quot;amountCurrency\&quot;: \&quot;${amountCurrency}\&quot;,\n        \&quot;chargeBearerCode\&quot;: \&quot;${chargeBearerCode}\&quot;,\n        \&quot;paymentInformation\&quot;: \&quot;${paymentInformation}\&quot;\n    }\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>${Content_Type}</value>
      <webElementGuid>991fec3b-bfa6-4517-ace2-60019ce9dfe8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-IP-ADDRESS</name>
      <type>Main</type>
      <value>${X_IP_ADDRESS}</value>
      <webElementGuid>300f736c-a587-406f-8498-89725e1bf564</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-DEVICE-ID</name>
      <type>Main</type>
      <value>${X_DEVICE_ID}</value>
      <webElementGuid>09c81924-cc73-471c-9b96-cac6804a7e56</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-LATITUDE</name>
      <type>Main</type>
      <value>${X_LATITUDE}</value>
      <webElementGuid>219a9c08-851c-4168-97f9-5c5c0f55e81e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-LONGITUDE</name>
      <type>Main</type>
      <value>${X_LONGITUDE}</value>
      <webElementGuid>54e842b8-a5ca-4222-9aaa-9ddaef089238</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>2de04c8f-ed7b-4536-ace8-71b44630457f</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.1.1</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${path}/invoke/KomiBifastOriginCT.interfaces:creditTransfer</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>79178c2e-b1d2-4f43-88ac-a3f0b9358cb6</id>
      <masked>false</masked>
      <name>Content_Type</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>63b7792d-2ace-4a16-8411-3b7dbded0a89</id>
      <masked>false</masked>
      <name>transactionId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7fd7b876-11a1-4984-9fc7-3a97c86ab75a</id>
      <masked>false</masked>
      <name>institutionBic</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>37fe348d-5c5e-4408-bd38-a83f6691a2b4</id>
      <masked>false</masked>
      <name>channelType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>14afc234-3f15-4a60-9ef1-e8cedbf50c87</id>
      <masked>false</masked>
      <name>branchCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>75831da8-57ca-469d-8877-485e1b91a055</id>
      <masked>false</masked>
      <name>branchInput</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8f70520f-9e99-404d-8308-2870ea8a0f40</id>
      <masked>false</masked>
      <name>branchFee</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4febee62-a73e-49c9-a41f-019e95f4f99d</id>
      <masked>false</masked>
      <name>debitedAccountName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c59e2693-db86-42f0-8d2d-4a78c91054bd</id>
      <masked>false</masked>
      <name>debitedAccountNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7e5b0b86-c4e3-4746-b15d-01afca36c748</id>
      <masked>false</masked>
      <name>debitedAccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ecbf84da-e054-48bf-8ea1-238cd356f5a0</id>
      <masked>false</masked>
      <name>debitedCityCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2a977e0f-52dd-4c70-a51e-6d24f9f4bbb3</id>
      <masked>false</masked>
      <name>debitedId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d1fd4540-7f02-4ec2-be3b-c9695513b78e</id>
      <masked>false</masked>
      <name>debitedResidentStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>977fef07-094a-4a93-895c-9bbf7466c93a</id>
      <masked>false</masked>
      <name>debitedType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>810e0c7d-8edf-4373-8736-808a5741a6fe</id>
      <masked>false</masked>
      <name>creditedAccountName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ce28b43c-14af-4275-afb1-46267eb12fe6</id>
      <masked>false</masked>
      <name>creditedAccountNumber</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>aff10d1d-6b9e-4a14-9744-86ce5fe304d9</id>
      <masked>false</masked>
      <name>creditedAccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0f4fce57-45e4-43d9-910b-ada49381a45a</id>
      <masked>false</masked>
      <name>creditedBic</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>eb5bc6ca-c6f6-4658-9943-aa2ce922c44c</id>
      <masked>false</masked>
      <name>creditedCityCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>60d50170-ec60-4491-8231-400a7b1ea2cd</id>
      <masked>false</masked>
      <name>creditedId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c4b69f11-7f2c-41e4-acf1-e4e954680bde</id>
      <masked>false</masked>
      <name>creditedProxyAlias</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>763a3932-079a-4d72-b30e-9fc790e66b9d</id>
      <masked>false</masked>
      <name>creditedProxyType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>84970af5-d0bb-4793-98db-5e8c154d9217</id>
      <masked>false</masked>
      <name>creditedResidentStatus</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>412ea6fd-ef34-4458-b7d2-92ae9ab853a2</id>
      <masked>false</masked>
      <name>creditedType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>35ed7522-4988-4da6-a8fe-bc32b55e09aa</id>
      <masked>false</masked>
      <name>categoryPurpose</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d1413279-3a69-4868-afc6-4eb7544a5a8f</id>
      <masked>false</masked>
      <name>chargeType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>30891b5d-6671-4cd6-b267-d560b34e51fc</id>
      <masked>false</masked>
      <name>trxAmount</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d6b896e7-7012-447b-b368-592be5978772</id>
      <masked>false</masked>
      <name>feeAmount</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>10f2ac8f-fa9f-41b2-8790-1ed0d32872df</id>
      <masked>false</masked>
      <name>amountCurrency</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9701d0a3-d2a6-4ff5-b3e6-520555d7f3c3</id>
      <masked>false</masked>
      <name>chargeBearerCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>390a1683-5961-4577-ad50-91fa5f0ff4b9</id>
      <masked>false</masked>
      <name>paymentInformation</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.IS_Postgres_Origin</defaultValue>
      <description></description>
      <id>cc821565-57e2-4274-80b9-5d28aa1d5f08</id>
      <masked>false</masked>
      <name>path</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e84182b6-fe0a-40cc-bc8f-6b6fa37e158d</id>
      <masked>false</masked>
      <name>X_IP_ADDRESS</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a3081832-a3c8-4865-b8e4-c704b345dcb8</id>
      <masked>false</masked>
      <name>X_DEVICE_ID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>151902ad-8bb7-4eb7-9744-a3684458396d</id>
      <masked>false</masked>
      <name>X_LATITUDE</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0406c368-1365-4a28-88b7-3fb54d0c5964</id>
      <masked>false</masked>
      <name>X_LONGITUDE</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
