<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>65. Successful Settlement Confirmation Credit Request</name>
   <tag></tag>
   <elementGuidId>75558cf7-1eae-427a-9e36-cbe73ef46676</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;receivingSettlementConfirmationRequest\&quot;: {\n\t\t\&quot;requestID\&quot;: \&quot;${requestID}\&quot;,\n\t\t\&quot;requestDate\&quot;: \&quot;${requestDate}\&quot;,\n\t\t\&quot;originalRequestID\&quot;: \&quot;${originalRequestID}\&quot;,\n\t\t\&quot;msgNmID\&quot;: \&quot;${msgNmID}\&quot;,\n\t\t\&quot;originalRequestDate\&quot;: \&quot;${originalRequestDate}\&quot;,\n\t\t\&quot;originalEnd2EndID\&quot;: \&quot;${originalEnd2EndID}\&quot;,\n\t\t\&quot;originalTransactionID\&quot;: \&quot;${originalTransactionID}\&quot;,\n\t\t\&quot;statusCode\&quot;: \&quot;${statusCode}\&quot;,\n\t\t\&quot;reasonCode\&quot;: \&quot;${reasonCode}\&quot;,\n\t\t\&quot;reasonAdditionalInfo\&quot;: \&quot;${reasonAdditionalInfo}\&quot;,\n\t\t\&quot;settlementDate\&quot;: \&quot;${settlementDate}\&quot;,\n\t\t\&quot;debitor\&quot;: {\n\t\t\t\&quot;name\&quot;: \&quot;${debitorname}\&quot;,\n\t\t\t\&quot;accountID\&quot;: \&quot;${debitoraccountID}\&quot;,\n\t\t\t\&quot;accountType\&quot;: \&quot;${debitoraccountType}\&quot;,\n\t\t\t\&quot;agentID\&quot;: \&quot;${debitoragentID}\&quot;,\n\t\t\t\&quot;type\&quot;: \&quot;${debitortype}\&quot;,\n\t\t\t\&quot;natID\&quot;: \&quot;${debitornatID}\&quot;,\n\t\t\t\&quot;rsdntSts\&quot;: \&quot;${debitorrsdntSts}\&quot;,\n\t\t\t\&quot;twnNm\&quot;: \&quot;${debitortwnNm}\&quot;,\n\t\t\t\&quot;settlementAccountID\&quot;: \&quot;${debitorsettlementAccountID}\&quot;\n\t\t},\n\t\t\&quot;creditor\&quot;: {\n\t\t\t\&quot;agentID\&quot;: \&quot;${creditoragentID}\&quot;,\n\t\t\t\&quot;name\&quot;: \&quot;${creditorname}\&quot;,\n\t\t\t\&quot;accountID\&quot;: \&quot;${creditoraccountID}\&quot;,\n\t\t\t\&quot;accountType\&quot;: \&quot;${creditoraccountType}\&quot;,\n\t\t\t\&quot;type\&quot;: \&quot;${creditortype}\&quot;,\n\t\t\t\&quot;natID\&quot;: \&quot;${creditornatID}\&quot;,\n\t\t\t\&quot;rsdntSts\&quot;: \&quot;${creditorrsdntSts}\&quot;,\n\t\t\t\&quot;twnNm\&quot;: \&quot;${creditortwnNm}\&quot;,\n\t\t\t\&quot;settlementAccountID\&quot;: \&quot;${creditorsettlementAccountID}\&quot;\n\t\t}\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d89492fd-3e2a-40e3-91d1-006429e47720</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>2c0b2ca6-a57d-4e4a-a499-586a6b8a7ba3</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${path}/invoke/KomiBifastReceivingCT.interfaces:settlementConfirmation</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.IS_Postgres_Incoming</defaultValue>
      <description></description>
      <id>b0f18fda-4867-4e00-8926-27e8a4d1842d</id>
      <masked>false</masked>
      <name>path</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b83e3516-e11d-431f-b70a-7b7a66f6e4cc</id>
      <masked>false</masked>
      <name>requestID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3bf8e0fe-5961-4c9b-88ad-f73c24660407</id>
      <masked>false</masked>
      <name>requestDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e64cae54-14e7-4a76-8d24-a2120780ad78</id>
      <masked>false</masked>
      <name>originalRequestID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4d2a72e2-1b57-403b-8034-3a92479ee033</id>
      <masked>false</masked>
      <name>msgNmID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a6f8e924-93bd-4ab0-b24b-34476d8e9e60</id>
      <masked>false</masked>
      <name>originalRequestDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1eb01b8e-e926-4201-92e8-9854d10b63d3</id>
      <masked>false</masked>
      <name>originalEnd2EndID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e7160a20-8da3-41ea-94df-7fffbbb92b9c</id>
      <masked>false</masked>
      <name>originalTransactionID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0dcfd5bb-8c87-4d51-959b-4b31360f4856</id>
      <masked>false</masked>
      <name>statusCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5edc9477-4047-428f-ac89-be8736705885</id>
      <masked>false</masked>
      <name>reasonCode</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a036474c-4396-4db4-862a-10481191837b</id>
      <masked>false</masked>
      <name>reasonAdditionalInfo</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1e381658-5353-41b2-ac45-36f68793500e</id>
      <masked>false</masked>
      <name>settlementDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>06480437-fe40-48c9-a9de-2780c6024dc5</id>
      <masked>false</masked>
      <name>debitorname</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f32d84d7-9336-41fa-bfb1-fbe4b465fdba</id>
      <masked>false</masked>
      <name>debitoraccountID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8b0ce880-b0a3-4c10-8a07-4f0c3e5a2fb7</id>
      <masked>false</masked>
      <name>debitoraccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>21c601c2-a690-494d-aa9b-3f2b06245f78</id>
      <masked>false</masked>
      <name>debitoragentID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1d87527f-5484-4084-8809-335a1b84eab7</id>
      <masked>false</masked>
      <name>debitortype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>06b3b3ff-8529-4346-8e5a-e4f7faa56a30</id>
      <masked>false</masked>
      <name>debitornatID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>18998e3a-e07d-42b5-af1d-c7d941aecbcf</id>
      <masked>false</masked>
      <name>debitorrsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>67ea7529-1950-41e3-8b0c-090f68bb041b</id>
      <masked>false</masked>
      <name>debitortwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6b75b890-d2b4-4967-a387-0f852acc6495</id>
      <masked>false</masked>
      <name>debitorsettlementAccountID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e174aa6b-0f33-4bc7-89eb-26324eb1f9b8</id>
      <masked>false</masked>
      <name>creditoragentID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e96943f8-7a68-4749-9186-bc32f95fa487</id>
      <masked>false</masked>
      <name>creditorname</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>01323f6f-b954-45f9-b51e-6bee90aa407a</id>
      <masked>false</masked>
      <name>creditoraccountID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49d9a3d1-10e1-4a2c-a97f-1fc941ac8058</id>
      <masked>false</masked>
      <name>creditoraccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e61b8231-68ba-4143-af07-f0f466f64785</id>
      <masked>false</masked>
      <name>creditortype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>382f125a-8669-4353-9901-8fa5211c24d7</id>
      <masked>false</masked>
      <name>creditornatID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>55901bd3-72d6-4278-bfc1-7cced835ff42</id>
      <masked>false</masked>
      <name>creditorrsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>888e502c-75e0-4837-95b5-86e5bd8d4eff</id>
      <masked>false</masked>
      <name>creditortwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c0514f1d-9d37-44f6-af77-c40d70a1e4a4</id>
      <masked>false</masked>
      <name>creditorsettlementAccountID</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
