<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>50. Credit Transfer - Failed - Invalid Mandatory Field Amount</name>
   <tag></tag>
   <elementGuidId>6f94aedb-3b4e-4646-ad04-4bac4445ee2c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;receivingCreditTransferRequest\&quot;: {\n\t\t\&quot;requestID\&quot;: \&quot;${requestID}\&quot;,\n\t\t\&quot;chargeBearer\&quot;: \&quot;${chargeBearer}\&quot;,\n\t\t\&quot;transactionPurpose\&quot;: \&quot;${transactionPurpose}\&quot;,\n\t\t\&quot;endToEndID\&quot;: \&quot;${endToEndID}\&quot;,\n\t\t\&quot;transactionID\&quot;: \&quot;${transactionID}\&quot;,\n\t\t\&quot;settlementCurrency\&quot;: \&quot;${settlementCurrency}\&quot;,\n\t\t\&quot;requestDate\&quot;: \&quot;${requestDate}\&quot;,\n\t\t\&quot;settlementAmount1\&quot;: \&quot;${settlementAmount}\&quot;,\n\t\t\&quot;settlementMethod\&quot;: \&quot;${settlementMethod}\&quot;,\n\t\t\&quot;originatingBIC\&quot;: \&quot;${originatingBIC}\&quot;,\n\t\t\&quot;receivingBIC\&quot;: \&quot;${receivingBIC}\&quot;,\n\t\t\&quot;debitor\&quot;: {\n\t\t\t\&quot;name\&quot;: \&quot;${debitorname}\&quot;,\n\t\t\t\&quot;natID\&quot;: \&quot;${debitornatID}\&quot;,\n\t\t\t\&quot;accountID\&quot;: \&quot;${debitoraccountID}\&quot;,\n\t\t\t\&quot;accountType\&quot;: \&quot;${debitoraccountType}\&quot;,\n\t\t\t\&quot;rsdntSts\&quot;: \&quot;${debitorrsdntSts}\&quot;,\n\t\t\t\&quot;twnNm\&quot;: \&quot;${debitortwnNm}\&quot;\n\t\t},\n\t\t\&quot;creditor\&quot;: {\n\t\t\t\&quot;name\&quot;: \&quot;${creditorname}\&quot;,\n\t\t\t\&quot;natID\&quot;: \&quot;${creditornatID}\&quot;,\n\t\t\t\&quot;accountID\&quot;: \&quot;${creditoraccountID}\&quot;,\n\t\t\t\&quot;proxyType\&quot;: \&quot;${creditorproxyType}\&quot;,\n\t\t\t\&quot;rsdntSts\&quot;: \&quot;${creditorrsdntSts}\&quot;,\n\t\t\t\&quot;type\&quot;: \&quot;${creditortype}\&quot;,\n\t\t\t\&quot;twnNm\&quot;: \&quot;${creditortwnNm}\&quot;\n\t\t}\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>ff09aa31-595c-4e0d-a1a4-22c5142a3d02</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d89492fd-3e2a-40e3-91d1-006429e47720</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${path}/invoke/KomiBifastReceivingCT.interfaces:creditTransfer</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a39344e6-624f-4d0c-a5be-2b8d9d0b1314</id>
      <masked>false</masked>
      <name>requestID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>80de4d66-260c-4896-a7ce-06068b09c6ec</id>
      <masked>false</masked>
      <name>chargeBearer</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c63c49af-a7e7-419a-9bc2-22704724d7ec</id>
      <masked>false</masked>
      <name>transactionPurpose</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c5910ae6-b538-404d-88f4-c6177946ba76</id>
      <masked>false</masked>
      <name>endToEndID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2c92d023-f2b7-4238-b065-b522c38fc77e</id>
      <masked>false</masked>
      <name>transactionID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5f4d65b3-3eec-4d6e-b0d8-58d7dce095fa</id>
      <masked>false</masked>
      <name>settlementCurrency</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>63f201b7-8097-436b-8b53-43d3706f3227</id>
      <masked>false</masked>
      <name>requestDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a47874c2-0f91-40a8-8256-c878193ce0ca</id>
      <masked>false</masked>
      <name>settlementAmount</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8ad445fc-43d3-43ed-977a-9ddd8e89795e</id>
      <masked>false</masked>
      <name>settlementMethod</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a0650b7c-ff40-4bc4-b461-cce149cd88a2</id>
      <masked>false</masked>
      <name>originatingBIC</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>20218c0e-15d6-47fe-a28e-58ddb4e54cff</id>
      <masked>false</masked>
      <name>receivingBIC</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>35ff733d-4968-4dc2-9001-bc79160fad2b</id>
      <masked>false</masked>
      <name>debitorname</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>225779f2-cf41-454c-a4ce-31b29f6897bc</id>
      <masked>false</masked>
      <name>debitornatID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>adb4f77d-992b-456e-8bea-92e11fc240dc</id>
      <masked>false</masked>
      <name>debitoraccountID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>32c4c844-61db-4110-ae5c-c21b87df7c20</id>
      <masked>false</masked>
      <name>debitoraccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>65270a7d-5b56-4404-809c-86f11c698723</id>
      <masked>false</masked>
      <name>debitorrsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f1b88162-398e-4105-bb3d-967e0f487403</id>
      <masked>false</masked>
      <name>debitortwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ac00e879-54d8-45b0-aac7-c45cd39c418c</id>
      <masked>false</masked>
      <name>creditorname</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b62ac309-9558-4c50-aaa1-f58fffd91a4e</id>
      <masked>false</masked>
      <name>creditornatID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c65550fe-fc5c-4b66-b898-aac4c89bca25</id>
      <masked>false</masked>
      <name>creditoraccountID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1d1c04f9-7871-4928-acfd-c69ede392045</id>
      <masked>false</masked>
      <name>creditorproxyType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>374ad572-f4a4-4b9c-ab50-d8ec5092285c</id>
      <masked>false</masked>
      <name>creditorrsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>96653593-d8e2-41b8-b398-0497ad759672</id>
      <masked>false</masked>
      <name>creditortype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b9132328-7004-40f6-a6c7-b630b9cc99fb</id>
      <masked>false</masked>
      <name>creditortwnNm</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.IS_Postgres_Incoming</defaultValue>
      <description></description>
      <id>b0f18fda-4867-4e00-8926-27e8a4d1842d</id>
      <masked>false</masked>
      <name>path</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
