<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>1. Proxy Porting - Sukses</name>
   <tag></tag>
   <elementGuidId>1f968d1d-41f7-4eca-a915-f9b37ace07b0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;receivingProxyNotifyPortingRequest\&quot;: {\n\t\t\&quot;requestID\&quot;: \&quot;${requestID}\&quot;,\n\t\t\&quot;requestDate\&quot;: \&quot;${requestDate}\&quot;,\n\t\t\&quot;recipientBIC\&quot;: \&quot;${recipientBIC}\&quot;,\n\t\t\&quot;originalID\&quot;: \&quot;${originalID}\&quot;,\n\t\t\&quot;proxyType\&quot;: \&quot;${proxyType}\&quot;,\n\t\t\&quot;proxyValue\&quot;: \&quot;${proxyValue}\&quot;,\n\t\t\&quot;originalAccount\&quot;: {\n\t\t\t\&quot;registrationID\&quot;: \&quot;${originalAccountregistrationID}\&quot;,\n\t\t\t\&quot;displayName\&quot;: \&quot;${originalAccountdisplayName}\&quot;,\n\t\t\t\&quot;bankID\&quot;: \&quot;${originalAccountbankID}\&quot;,\n\t\t\t\&quot;accountIdentifier\&quot;: \&quot;${originalAccountaccountIdentifier}\&quot;,\n\t\t\t\&quot;accountType\&quot;: \&quot;${originalAccountaccountType}\&quot;,\n\t\t\t\&quot;accountName\&quot;: \&quot;${originalAccountaccountName}\&quot;,\n\t\t\t\&quot;customerType\&quot;: \&quot;${originalAccountcustomerType}\&quot;,\n\t\t\t\&quot;customerID\&quot;: \&quot;${originalAccountcustomerID}\&quot;,\n\t\t\t\&quot;customerRsdntSts\&quot;: \&quot;${originalAccountcustomerRsdntSts}\&quot;,\n\t\t\t\&quot;customerTwnNm\&quot;: \&quot;${originalAccountcustomerTwnNm}\&quot;\n\t\t},\n\t\t\&quot;newAccount\&quot;: {\n\t\t\t\&quot;registrationID\&quot;: \&quot;${newAccountregistrationID}\&quot;,\n\t\t\t\&quot;displayName\&quot;: \&quot;${newAccountdisplayName}\&quot;,\n\t\t\t\&quot;bankID\&quot;: \&quot;${newAccountbankID}\&quot;,\n\t\t\t\&quot;accountIdentifier\&quot;: \&quot;${newAccountaccountIdentifier}\&quot;,\n\t\t\t\&quot;accountType\&quot;: \&quot;${newAccountaccountType}\&quot;,\n\t\t\t\&quot;accountName\&quot;: \&quot;${newAccountaccountName}\&quot;,\n\t\t\t\&quot;customerType\&quot;: \&quot;${newAccountcustomerType}\&quot;,\n\t\t\t\&quot;customerID\&quot;: \&quot;${newAccountcustomerID}\&quot;,\n\t\t\t\&quot;customerRsdntSts\&quot;: \&quot;${newAccountcustomerRsdntSts}\&quot;,\n\t\t\t\&quot;customerTwnNm\&quot;: \&quot;${newAccountcustomerTwnNm}\&quot;\n\t\t}\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>991fec3b-bfa6-4517-ace2-60019ce9dfe8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic dXNlcmNoYW5uZWw6dXNlcmNoYW5uZWwxMjM=</value>
      <webElementGuid>8b173e1d-0cb8-4735-90e6-88a3d4800b84</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.1.1</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${path}/invoke/KomiBifastReceivingProxy.interfaces:notifyPorting</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.IS_ORACLE_Incoming</defaultValue>
      <description></description>
      <id>cc821565-57e2-4274-80b9-5d28aa1d5f08</id>
      <masked>false</masked>
      <name>path</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9cdf14fc-ee4c-48ec-8300-54b48564fd0c</id>
      <masked>false</masked>
      <name>requestID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7ec639d5-e822-4285-9be3-fe632af0908e</id>
      <masked>false</masked>
      <name>requestDate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8b1a2f95-4739-4f12-bacb-88937945071d</id>
      <masked>false</masked>
      <name>recipientBIC</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f3f041ba-2328-403e-af56-242f6f0c4ce0</id>
      <masked>false</masked>
      <name>originalID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c29b1673-20a6-4ac1-b225-64a18a1db4af</id>
      <masked>false</masked>
      <name>proxyType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>effd71df-fd1b-4119-8ee5-e6ac9979ef87</id>
      <masked>false</masked>
      <name>proxyValue</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cb21d11d-e986-450a-a4c0-65be653559e9</id>
      <masked>false</masked>
      <name>originalAccountregistrationID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>85073afd-d4fe-438e-bfc7-4dedb05ed889</id>
      <masked>false</masked>
      <name>originalAccountdisplayName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a4877ac1-b262-4f94-85ee-f092df18346e</id>
      <masked>false</masked>
      <name>originalAccountbankID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>05bac4bb-4877-4b01-aa11-2e42ff00dfd6</id>
      <masked>false</masked>
      <name>originalAccountaccountIdentifier</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c7b1630f-5ea2-41d7-a1b1-a235fd7a904a</id>
      <masked>false</masked>
      <name>originalAccountaccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ac3273a3-267d-429c-b179-a888e56dec45</id>
      <masked>false</masked>
      <name>originalAccountaccountName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>af9a364c-90c9-4273-8498-96a289b7e50b</id>
      <masked>false</masked>
      <name>originalAccountcustomerType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d96c74a1-e2d8-4d3d-baf6-8f8b2517c6c2</id>
      <masked>false</masked>
      <name>originalAccountcustomerID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>01180bf2-6fa5-4539-a2ea-d20089b27d29</id>
      <masked>false</masked>
      <name>originalAccountcustomerRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e697bd29-5bb8-45ff-931d-3f7cbcc639ed</id>
      <masked>false</masked>
      <name>originalAccountcustomerTwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b63f60b4-a6f3-4d66-9237-6e74a917c21b</id>
      <masked>false</masked>
      <name>newAccountregistrationID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>be9142a3-76d7-4088-86a3-28723a7c7a32</id>
      <masked>false</masked>
      <name>newAccountdisplayName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c8ed86a8-e938-46f2-a4c5-8c68dfd5801a</id>
      <masked>false</masked>
      <name>newAccountbankID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f9f97fc6-8b2c-4501-80bf-48abe465c61a</id>
      <masked>false</masked>
      <name>newAccountaccountIdentifier</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fd06f075-682a-4c38-824a-d7a4611c4f8d</id>
      <masked>false</masked>
      <name>newAccountaccountType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>78c875a9-45bb-4b1c-8c3c-1018cb38d351</id>
      <masked>false</masked>
      <name>newAccountaccountName</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f9558864-3849-419f-8318-1b9c4c8ab5a9</id>
      <masked>false</masked>
      <name>newAccountcustomerType</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c8977438-0a34-47bf-9949-0e59624ee1fd</id>
      <masked>false</masked>
      <name>newAccountcustomerID</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d64e287d-24e5-4209-9348-325d355f674c</id>
      <masked>false</masked>
      <name>newAccountcustomerRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6cf100d0-9fdf-4d30-9bbd-d6f69caeea07</id>
      <masked>false</masked>
      <name>newAccountcustomerTwnNm</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
